# devdock: Shell-Setup im Container, wird aus ~/.bashrc gesourct

export EDITOR=nvim
export VISUAL=nvim

eval "$(mise activate bash)"

alias vim=nvim
alias lg=lazygit
alias lzd=lazydocker

# bash-preexec muss vor starship und atuin geladen sein: Beide hängen sich dann
# in precmd_functions/preexec_functions ein, statt sich gegenseitig die
# DEBUG-Trap und PROMPT_COMMAND zu überschreiben.
if [[ -f ~/.bash-preexec.sh ]]; then
  source ~/.bash-preexec.sh
fi

eval "$(starship init bash)"

eval "$(zoxide init --cmd cd bash)"

eval "$(atuin init bash --disable-up-arrow)"
